### ISSUE TITLE
clip animation

### ISSUE THREAD

**Issue by j11k00** [CodyHouse/cd-animated-headline-changelog#1]
Hi, the clip animation stopped working when i uppdated the framework in my project.
The console throws an error. Math.easeInOutQuart is not a function
All other animations work as before.

**Comment by claudia-romano** [comment]
Hi there, did you update the util.js function of the framework as well? 
The new version includes the new Math.easeInOutQuart function. Cheers!

**Comment by j11k00** [comment]
Oh! no I didn't... My bad! Works after updating the the util.js file. Thanks for the quick reply.
